// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

let __config = new pulumi.Config("digitalocean");

/**
 * The token key for API operations.
 */
export let token: string = __config.require("token");
